#!/usr/bin/bash

# https://github.com/elm/compiler/blob/master/hints/optimize.md

js="elmain.js"

echo "Initial size: $(cat $js | wc -c) bytes"

uglifyjs $js --compress "pure_funcs=[F2,F3,F4,F5,F6,F7,F8,F9,A2,A3,A4,A5,A6,A7,A8,A9],pure_getters,keep_fargs=false,unsafe_comps,unsafe" | uglifyjs --mangle --output $js

echo "Minified size:$(cat $js | wc -c) bytes"
echo "Gzipped size: $(cat $js | gzip -c | wc -c) bytes"
